; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed Aug 11 2021 18:32:48 GMT+0100 (British Summer Time)
; ================================================================================

DATAZEB5V6JRJ3H:
	dc.w DATAZEB5V6JRJ3H_0-DATAZEB5V6JRJ3H, DATAZEB5V6JRJ3H_1-DATAZEB5V6JRJ3H
	dc.w DATAZEB5V6JRJ3H_2-DATAZEB5V6JRJ3H, DATAZEB5V6JRJ3H_3-DATAZEB5V6JRJ3H
	dc.w DATAZEB5V6JRJ3H_4-DATAZEB5V6JRJ3H, DATAZEB5V6JRJ3H_5-DATAZEB5V6JRJ3H
	dc.w DATAZEB5V6JRJ3H_6-DATAZEB5V6JRJ3H, DATAZEB5V6JRJ3H_7-DATAZEB5V6JRJ3H
	dc.w DATAZEB5V6JRJ3H_8-DATAZEB5V6JRJ3H
DATAZEB5V6JRJ3H_0: dc.b $1
	dc.b $EF, $F, $0, $0, $F0
DATAZEB5V6JRJ3H_1: dc.b $1
	dc.b $F8, $0, $0, $0, $FC
DATAZEB5V6JRJ3H_2: dc.b $1
	dc.b $F8, $0, $0, $1, $FC
DATAZEB5V6JRJ3H_3: dc.b $1
	dc.b $F8, $1, $0, $2, $FC
DATAZEB5V6JRJ3H_4: dc.b $1
	dc.b $F8, $1, $0, $4, $FC
DATAZEB5V6JRJ3H_5: dc.b $1
	dc.b $F8, $1, $0, $6, $FC
DATAZEB5V6JRJ3H_6: dc.b $1
	dc.b $F8, $5, $0, $8, $F8
DATAZEB5V6JRJ3H_7: dc.b $1
	dc.b $F8, $5, $0, $C, $F8
DATAZEB5V6JRJ3H_8: dc.b $1
	dc.b $F0, $F, $0, $10, $F0
	even