; ================================================================================
; Sprite Mappings - generated by Flex 2 Fri Dec 18 2020 22:05:21 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATAYDZD849MEMA:
	dc.w DATAYDZD849MEMA_0-DATAYDZD849MEMA
DATAYDZD849MEMA_0: dc.b $3
	dc.b $E8, $F, $0, $0, $F0
	dc.b $8, $8, $0, $10, $F0
	dc.b $10, $0, $0, $13, $0
	even