; ================================================================================
; Sprite Mappings - generated by Flex 2 Sun Dec 20 2020 17:48:20 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATAQZ9CZ11E8T:
	dc.w DATAQZ9CZ11E8T_0-DATAQZ9CZ11E8T
DATAQZ9CZ11E8T_0: dc.b $3
	dc.b $F4, $C, $0, $0, $F0
	dc.b $FC, $1, $0, $4, $F0
	dc.b $FC, $1, $0, $6, $8
	even