; ================================================================================
; Sprite Mappings - generated by Flex 2 Fri Dec 18 2020 22:06:55 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATAUI6DX8OCWY:
	dc.w DATAUI6DX8OCWY_0-DATAUI6DX8OCWY
DATAUI6DX8OCWY_0: dc.b $1
	dc.b $F4, $E, $0, $0, $F0
	even